// NOTE: This file is automatically generated by build.rs. Do not edit manually.
// 自动扫描 logic 目录下的 handlers。
// 规则: 带有 help_msg 的 handler 放入 command 列表, 否则放入 other 列表。
// 假设: 所有 Handler 结构体都通过其模块的根路径暴露 (例如 `echo::EchoHandler`, `login::LoginHandler`)。
