// NOTE: This file is automatically generated by build.rs. Do not edit manually.
// 自动扫描 logic 目录下的 handlers。
// 规则: 带有 help_msg 的 handler 放入 command 列表, 否则放入 other 列表。
// 假设: 所有 Handler 结构体都通过其模块的根路径暴露 (例如 `echo::EchoHandler`, `login::LoginHandler`)。

mod classroom;
mod download;
mod echo;
mod fate;
mod helper;
mod image;
mod llm;
mod login;
mod test;
mod timetable;

use crate::abi::logic_import::*;

pub trait BuildHelp {
    const HELP_MSG: &'static str;
}

register_handler_with_help!(
    command = [
        classroom::ClassHandler,
        classroom::GetClassHandler,
        download::DownloadHandler,
        echo::EchoHandler,
        fate::FateHandler,
        image::ImageHandler,
        login::LoginHandler,
        login::LogoutHandler,
        test::TestHandler,
        test::GetTestHandler,
        test::TestAnsHandler,
        timetable::TimetableHandler
    ],
    other = [
        llm::LlmMessageHandler,
        llm::LlmNoticeHandler
    ]
);
